apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: edgenius
  name: dataapi
  labels:
    app: dataapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataapi
  template:
    metadata:
      labels:
        app: dataapi
    spec:
      containers:
        - name: dataapi
          image: griffins.azurecr.io/edge-demo-data-api:1.0.51
          env:
            - name: otel_exporter_url
              value: "http://otel-demo-collector.edgenius.svc.cluster.local:4317"
            - name: varialbe_api_url
              value: "http://variableapi.edgenius.svc.cluster.local"
            - name: event_api_url
              value: "http://eventapi.edgenius.svc.cluster.local"
            - name: assetdb_api_url
              value: "http://assetdbapi.edgenius.svc.cluster.local"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: griffinsreg