---
- hosts: nodes
  gather_facts: true
  roles:
    - role: build_config
    - role: common/set_host_name
    - role: common/update_etc_hosts

- hosts: cluster
  roles:
    - role: common/disable_swap
    - role: common/install_kube_packages
    - role: common/configure_network

- hosts: controllers
  roles:
    - role: add_control_plane
    - role: bootstrap/copy_kubeconfig

- hosts: bootstrap
  roles:
    - role: bootstrap/install_packages
    - role: install_apps/calico

- hosts: workers
  roles:
    - role: add_workers

- hosts: bootstrap
  roles:
    - role: install_apps/metrics_server