---
- hosts: nodes
  gather_facts: true
  roles:
    - role: build_config
    - role: common/set_host_name
    - role: common/update_etc_hosts

- hosts: cluster
  gather_facts: true
  roles:
    - role: common/disable_swap
    - role: common/install_kube_packages
    - role: common/configure_network