---
- hosts: all
  gather_facts: true
  roles:
    - role: build_config
    - role: common/set_host_name
    - role: common/update_etc_hosts

- hosts: nodes
  roles:
    - role: nodes/disable_swap
    - role: nodes/install_kube_packages
    - role: nodes/configure_network

- hosts: controllers
  roles:
    - role: add_control_plane
    - role: bootstrap/copy_kubeconfig

- hosts: bootstrap
  roles:
    - role: bootstrap/install_packages
    - role: install_apps/calico

- hosts: workers
  roles:
    - role: add_workers

- hosts: bootstrap
  roles:
    - role: install_apps/metrics_server
    - role: install_apps/k8s-dashboard