apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: otel-edgenius-metrics
  name: otel-edgenius-metrics
  namespace: edgenius
spec:
  ports:
  - name: prometheus
    port: 8080
  selector:
    app.kubernetes.io/name: otel-edgenius-collector