apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-edgenius
  namespace: edgenius
spec:
  endpoints:
  - port: prometheus
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-edgenius-metrics