- name: Add chart repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Deploy cert-manager
  kubernetes.core.helm:
    name: cert-manager
    release_namespace: cert-manager
    create_namespace: true
    chart_ref: jetstack/cert-manager
    values:
      installCRDs: true

- name: Wait till the pods are in running phase
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: cert-manager
  register: cert_manager_pod_info
  until: cert_manager_pod_info | json_query('resources[*].status.phase') | unique == ["Running"]
  delay: 20
  retries: 12