apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-edgenius-collector-monitoring
  namespace: edgenius
spec:
  endpoints:
  - port: monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-edgenius-collector-monitoring