- name: Add chart repo
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: "https://kubernetes.github.io/ingress-nginx"

- name: Deploy ingress-nginx
  kubernetes.core.helm:
    name: ingress-nginx
    release_namespace: ingress-nginx
    create_namespace: true
    chart_ref: ingress-nginx/ingress-nginx
    
- name: Wait till the pods are in running phase
  include_role:
    name: install_apps/wait_for_pods
  vars:
    namespace: ingress-nginx
    delay: 30
    retries: 12 