apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: rpc-app
    release: prometheus
  name: rpc-app
  namespace: monitoring
spec:
  endpoints:
  - port: web
  selector:
    matchLabels:
      app: rpc-app
  namespaceSelector:
    matchNames:
      - default