- name: Create manifests directory
  file:
    path: "{{ calico_dir }}"
    state: directory

- name: Download tigera operator
  get_url:
    url: "https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/tigera-operator.yaml"
    dest: "{{ calico_dir }}"

- name: Install the Tigera Calico operator
  kubernetes.core.k8s:
    state: present
    src: "{{ calico_dir }}/tigera-operator.yaml"

- name: Wait till the pods are in running phase
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: tigera-operator
  register: tigera_operator_pod_info
  until: tigera_operator_pod_info | json_query('resources[*].status.phase') | unique == ["Running"]
  delay: 10
  retries: 12

- name: Copy manifest
  template:
    src: "{{ item }}"
    dest: "{{ calico_dir }}/{{ item }}"
  with_items:
    - custom-resources.yaml

- name: Install calico
  kubernetes.core.k8s:
    state: present
    src: "{{ calico_dir }}/custom-resources.yaml"

- name: Wait till the pods are in running phase
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: calico-system
  register: calico_system_pod_info
  until: calico_system_pod_info | json_query('resources[*].status.phase') | unique == ["Running"]
  delay: 20
  retries: 12