- name: Add chart repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: "https://charts.longhorn.io"

- name: Deploy longhorn
  kubernetes.core.helm:
    name: longhorn
    release_namespace: longhorn-system
    create_namespace: true
    chart_ref: longhorn/longhorn 
    chart_version: 1.4.1

- name: Wait till the pods are in running phase
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: longhorn-system
  register: longhorn_pod_info
  until: longhorn_pod_info | json_query('resources[*].status.phase') | unique == ["Running"]
  delay: 30
  retries: 12

- name: Ingress for longhorn ui
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/files/ingress.yaml"