- name: Add chart repo
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: "https://metallb.github.io/metallb"

- name: Deploy metallb
  kubernetes.core.helm:
    name: metallb
    release_namespace: metallb-system
    create_namespace: true
    chart_ref: metallb/metallb

- name: Wait till the pods are in running phase
  include_role:
    name: install_apps/wait_for_pods
  vars:
    namespace: metallb-system
    delay: 30
    retries: 12 

- name: Configure metallb
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
    namespace: metallb-system
  with_items:
    - "{{ role_path }}/files/ip_address_pool.yaml"
    - "{{ role_path }}/files/l2_advertisement.yaml"