- name: Add prometheus-community chart repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"

- name: Deploy prometheus
  kubernetes.core.helm:
    name: prometheus
    release_namespace: monitoring
    create_namespace: true
    chart_ref: prometheus-community/kube-prometheus-stack
    values: "{{ lookup('file', 'values.yaml') | from_yaml }}"

- name: Wait till the pods are in running phase
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: monitoring
  register: monitoring_pod_info
  until: monitoring_pod_info | json_query('resources[*].status.phase') | unique == ["Running"]
  delay: 20
  retries: 12