- name: Add prometheus-community chart repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"

- name: Deploy prometheus
  kubernetes.core.helm:
    name: prometheus
    release_namespace: observability
    create_namespace: true
    chart_ref: prometheus-community/kube-prometheus-stack
    values: "{{ lookup('file', 'values.yaml') | from_yaml }}"

- name: Wait till the pods are in running phase
  include_role:
    name: install_apps/wait_for_pods
  vars:
    namespace: observability
    delay: 30
    retries: 12

- name: Create rbac for prometheus instance in edgenius
  kubernetes.core.k8s:
    namespace: edgenius
    state: present
    src: "{{ role_path }}/files/prometheus_edgenius_rbac.yaml"

- name: Create prometheus instance for edgenius
  kubernetes.core.k8s:
    namespace: edgenius
    state: present
    src: "{{ role_path }}/files/prometheus_edgenius.yaml"

- name: Wait till the pods are in running phase
  include_role:
    name: install_apps/wait_for_pods
  vars:
    namespace: edgenius
    delay: 30
    retries: 12
  
- name: Create service for prometheus instance in edgenius
  kubernetes.core.k8s:
    namespace: edgenius
    state: present
    src: "{{ role_path }}/files/prometheus_edgenius_service.yaml"

- name: Create ingress for prometheus instance in edgenius
  kubernetes.core.k8s:
    namespace: edgenius
    state: present
    src: "{{ role_path }}/files/prometheus_edgenius_ingress.yaml"