- name: Add chart repo
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"

- name: Deploy mongodb
  kubernetes.core.helm:
    name: mongodb
    release_namespace: mongo
    create_namespace: true
    chart_ref: bitnami/mongodb
    values:
      auth:
        rootPassword: "welcome123#"
      persistence:
        storageClass: "longhorn"
        size: "2Gi"
      service:
        type: LoadBalancer
        loadBalancerIP: "192.168.0.181"

- name: Wait till the pods are in running phase
  include_role:
    name: install_apps/wait_for_pods
  vars:
    namespace: mongo
    delay: 30
    retries: 12 