apiVersion: v1
kind: Service
metadata:
  name: rpc-app-service
  labels:
    app: rpc-app
    release: prometheus
  namespace: edgenius
spec:
  ports:
  - name: web
    nodePort: 31001
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: rpc-app
  type: NodePort