apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-demo
  namespace: edgenius
spec:
  mode: deployment # This configuration is omittable.
  config: |
    receivers:
      otlp:
        protocols:
          http:
          grpc:
            endpoint: "0.0.0.0:4317"

    processors:

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8089"
        namespace: edgenius
        send_timestamps: true
        metric_expiration: 180m
        resource_to_telemetry_conversion:
          enabled: true
      jaeger:
        endpoint: "jaeger-demo-collector.observability.svc.cluster.local:14250"
        tls:
          insecure: true
      logging:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [jaeger]
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [prometheus]
      telemetry:
        logs:
          level: "debug"