apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: edgenius-otel-prometheus
  name: edgenius-otel-prometheus
  namespace: edgenius
spec:
  ports:
  - name: prometheus
    port: 8089
  selector:
    app.kubernetes.io/name: otel-demo-collector