apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: edgenius-otel-prometheus
  namespace: edgenius
spec:
  endpoints:
  - port: prometheus
  selector:
    matchLabels:
      app.kubernetes.io/name: edgenius-otel-prometheus