- name: Install metrics server
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/files/components.yaml"

- name: Wait till the pods are in running phase
  include_role:
    name: install_apps/wait_for_pods
  vars:
    namespace: kube-system
    delay: 30
    retries: 12 