apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: default-prometheus
  name: default-prometheus
  namespace: default
spec:
  image: quay.io/prometheus/prometheus:v2.42.0
  nodeSelector:
    kubernetes.io/os: linux
  replicas: 1
  resources:
    requests:
      memory: 400Mi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: default-prometheus
  version: v2.42.0
  serviceMonitorNamespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - default
  serviceMonitorSelector: {}